/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.PaymentGUI;

/**
 *
 * @author admin
 */
public class PaymentMainWindow extends javax.swing.JPanel {

    /**
     * Creates new form PaymentMainWindow
     */
    public PaymentMainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton1 = new javax.swing.JLabel();
        panelBorder2 = new GUI.PaymentGUI.Components.PanelBorder();
        ButtonCash = new GUI.PaymentGUI.Components.PaymentMainWindowCashButton();
        ButtonQrCode = new GUI.PaymentGUI.Components.PaymentMainWindowQrCodeButton();
        ButtonTrue = new GUI.PaymentGUI.Components.PaymentMainWindowTrueButton();
        ButtonPanel = new GUI.PaymentGUI.Components.Button();
        buttonCancel = new java.awt.Label();
        label1 = new java.awt.Label();
        ProductName = new java.awt.Label();
        ProductValue = new java.awt.Label();
        ProductImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(66, 56, 63));
        setPreferredSize(new java.awt.Dimension(720, 830));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BackButton1.setForeground(new java.awt.Color(255, 255, 255));
        BackButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Vector (3).png"))); // NOI18N
        BackButton1.setText("BACK");
        add(BackButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        panelBorder2.setMinimumSize(new java.awt.Dimension(0, 0));
        panelBorder2.setPreferredSize(new java.awt.Dimension(720, 730));
        panelBorder2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelBorder2.add(ButtonCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 299, -1, -1));
        panelBorder2.add(ButtonQrCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 299, -1, -1));
        panelBorder2.add(ButtonTrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 464, -1, -1));

        ButtonPanel.setBackground(new java.awt.Color(163, 43, 43));

        buttonCancel.setAlignment(java.awt.Label.CENTER);
        buttonCancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonCancel.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancel.setText("Cancel Order");

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        panelBorder2.add(ButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 640, -1, -1));

        label1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label1.setText("Choose Your Payment Method");
        panelBorder2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 28, -1, -1));

        ProductName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ProductName.setText("Product Name");
        panelBorder2.add(ProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 251, -1, -1));

        ProductValue.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ProductValue.setForeground(new java.awt.Color(238, 114, 0));
        ProductValue.setText("0 ฿");
        panelBorder2.add(ProductValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 251, 48, -1));

        ProductImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/imgPayment.png"))); // NOI18N
        panelBorder2.add(ProductImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 720, -1));

        add(panelBorder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackButton1;
    private GUI.PaymentGUI.Components.PaymentMainWindowCashButton ButtonCash;
    private GUI.PaymentGUI.Components.Button ButtonPanel;
    private GUI.PaymentGUI.Components.PaymentMainWindowQrCodeButton ButtonQrCode;
    private GUI.PaymentGUI.Components.PaymentMainWindowTrueButton ButtonTrue;
    private javax.swing.JLabel ProductImg;
    private java.awt.Label ProductName;
    private java.awt.Label ProductValue;
    private java.awt.Label buttonCancel;
    private java.awt.Label label1;
    private GUI.PaymentGUI.Components.PanelBorder panelBorder2;
    // End of variables declaration//GEN-END:variables
}
