/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.MenuComponent;

import GUI.Components.pnlBorder;
import java.awt.Color;

/**
 *
 * @author Adam
 */
public class CatagoryGUI extends javax.swing.JPanel {

    /**
     * Creates new form CatagoryGUI
     */
    public CatagoryGUI() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recommendButton = new GUI.Components.pnlBorder();
        recommendText = new javax.swing.JLabel();
        coffeeButton = new GUI.Components.pnlBorder();
        coffeeText = new javax.swing.JLabel();
        teaButton = new GUI.Components.pnlBorder();
        teaText = new javax.swing.JLabel();
        milkAndCocoaButton = new GUI.Components.pnlBorder();
        milkandcocoaText = new javax.swing.JLabel();
        juiceButton = new GUI.Components.pnlBorder();
        juiceText = new javax.swing.JLabel();
        sodaButton = new GUI.Components.pnlBorder();
        sodaText = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 55));

        recommendButton.setBackground(new java.awt.Color(246, 230, 230));
        recommendButton.setPreferredSize(new java.awt.Dimension(110, 100));
        recommendButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recommendText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        recommendText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recommendText.setText("Recommend");
        recommendButton.add(recommendText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 30));

        add(recommendButton);

        coffeeButton.setBackground(new java.awt.Color(246, 230, 230));
        coffeeButton.setPreferredSize(new java.awt.Dimension(110, 100));
        coffeeButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coffeeText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        coffeeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coffeeText.setText("Coffee");
        coffeeButton.add(coffeeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 30));

        add(coffeeButton);

        teaButton.setBackground(new java.awt.Color(246, 230, 230));
        teaButton.setPreferredSize(new java.awt.Dimension(110, 100));
        teaButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teaText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teaText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teaText.setText("Tea");
        teaButton.add(teaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 30));

        add(teaButton);

        milkAndCocoaButton.setBackground(new java.awt.Color(246, 230, 230));
        milkAndCocoaButton.setPreferredSize(new java.awt.Dimension(110, 100));
        milkAndCocoaButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        milkandcocoaText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        milkandcocoaText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milkandcocoaText.setText("Milk and cocoa");
        milkAndCocoaButton.add(milkandcocoaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 30));

        add(milkAndCocoaButton);

        juiceButton.setBackground(new java.awt.Color(246, 230, 230));
        juiceButton.setPreferredSize(new java.awt.Dimension(110, 100));
        juiceButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        juiceText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        juiceText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        juiceText.setText("Juice");
        juiceText.setAutoscrolls(true);
        juiceButton.add(juiceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 96, 40));

        add(juiceButton);

        sodaButton.setBackground(new java.awt.Color(246, 230, 230));
        sodaButton.setMinimumSize(new java.awt.Dimension(110, 100));
        sodaButton.setPreferredSize(new java.awt.Dimension(110, 100));
        sodaButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sodaText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sodaText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sodaText.setText("Soda");
        sodaButton.add(sodaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 30));

        add(sodaButton);
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.Components.pnlBorder coffeeButton;
    private javax.swing.JLabel coffeeText;
    private GUI.Components.pnlBorder juiceButton;
    private javax.swing.JLabel juiceText;
    private GUI.Components.pnlBorder milkAndCocoaButton;
    private javax.swing.JLabel milkandcocoaText;
    private GUI.Components.pnlBorder recommendButton;
    private javax.swing.JLabel recommendText;
    private GUI.Components.pnlBorder sodaButton;
    private javax.swing.JLabel sodaText;
    private GUI.Components.pnlBorder teaButton;
    private javax.swing.JLabel teaText;
    // End of variables declaration//GEN-END:variables

    public pnlBorder getCoffeeButton() {
        return coffeeButton;
    }

    public pnlBorder getJuiceButton() {
        return juiceButton;
    }

    public pnlBorder getMilkAndCocoaButton() {
        return milkAndCocoaButton;
    }

    public pnlBorder getRecommendButton() {
        return recommendButton;
    }

    public pnlBorder getSodaButton() {
        return sodaButton;
    }

    public pnlBorder getTeaButton() {
        return teaButton;
    }
    
}
