/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.MenuComponent;

import java.awt.Color;

/**
 *
 * @author Adam
 */
public class CatagoryGUI extends javax.swing.JPanel {

    /**
     * Creates new form CatagoryGUI
     */
    public CatagoryGUI() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecommentButton = new GUI.Components.pnlBorder();
        RecommentText = new javax.swing.JLabel();
        CoffeeButton = new GUI.Components.pnlBorder();
        CoffeeText = new javax.swing.JLabel();
        TeaButton = new GUI.Components.pnlBorder();
        TeaText = new javax.swing.JLabel();
        MilkAndCocoaButton = new GUI.Components.pnlBorder();
        MilkAndCocoaText = new javax.swing.JLabel();
        JuiceButton = new GUI.Components.pnlBorder();
        JuiceText = new javax.swing.JLabel();
        SodaButton = new GUI.Components.pnlBorder();
        SodaText = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 55));

        RecommentButton.setBackground(new java.awt.Color(246, 230, 230));

        RecommentText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RecommentText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecommentText.setText("Recomment");
        RecommentText.setAutoscrolls(true);

        javax.swing.GroupLayout RecommentButtonLayout = new javax.swing.GroupLayout(RecommentButton);
        RecommentButton.setLayout(RecommentButtonLayout);
        RecommentButtonLayout.setHorizontalGroup(
            RecommentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RecommentButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RecommentText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        RecommentButtonLayout.setVerticalGroup(
            RecommentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecommentButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RecommentText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        add(RecommentButton);

        CoffeeButton.setBackground(new java.awt.Color(246, 230, 230));
        CoffeeButton.setPreferredSize(new java.awt.Dimension(108, 100));

        CoffeeText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CoffeeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CoffeeText.setText("Coffee");
        CoffeeText.setAutoscrolls(true);

        javax.swing.GroupLayout CoffeeButtonLayout = new javax.swing.GroupLayout(CoffeeButton);
        CoffeeButton.setLayout(CoffeeButtonLayout);
        CoffeeButtonLayout.setHorizontalGroup(
            CoffeeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CoffeeButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoffeeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CoffeeButtonLayout.setVerticalGroup(
            CoffeeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoffeeButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CoffeeText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        add(CoffeeButton);

        TeaButton.setBackground(new java.awt.Color(246, 230, 230));
        TeaButton.setPreferredSize(new java.awt.Dimension(108, 100));

        TeaText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TeaText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TeaText.setText("Tea");
        TeaText.setAutoscrolls(true);

        javax.swing.GroupLayout TeaButtonLayout = new javax.swing.GroupLayout(TeaButton);
        TeaButton.setLayout(TeaButtonLayout);
        TeaButtonLayout.setHorizontalGroup(
            TeaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeaButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TeaText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TeaButtonLayout.setVerticalGroup(
            TeaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeaButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TeaText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        add(TeaButton);

        MilkAndCocoaButton.setBackground(new java.awt.Color(246, 230, 230));
        MilkAndCocoaButton.setPreferredSize(new java.awt.Dimension(108, 100));

        MilkAndCocoaText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MilkAndCocoaText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MilkAndCocoaText.setText("Milk and cocoa");
        MilkAndCocoaText.setAutoscrolls(true);

        javax.swing.GroupLayout MilkAndCocoaButtonLayout = new javax.swing.GroupLayout(MilkAndCocoaButton);
        MilkAndCocoaButton.setLayout(MilkAndCocoaButtonLayout);
        MilkAndCocoaButtonLayout.setHorizontalGroup(
            MilkAndCocoaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MilkAndCocoaButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MilkAndCocoaText)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        MilkAndCocoaButtonLayout.setVerticalGroup(
            MilkAndCocoaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MilkAndCocoaButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MilkAndCocoaText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        add(MilkAndCocoaButton);

        JuiceButton.setBackground(new java.awt.Color(246, 230, 230));
        JuiceButton.setPreferredSize(new java.awt.Dimension(108, 100));

        JuiceText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JuiceText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JuiceText.setText("Juice");
        JuiceText.setAutoscrolls(true);

        javax.swing.GroupLayout JuiceButtonLayout = new javax.swing.GroupLayout(JuiceButton);
        JuiceButton.setLayout(JuiceButtonLayout);
        JuiceButtonLayout.setHorizontalGroup(
            JuiceButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JuiceButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JuiceText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JuiceButtonLayout.setVerticalGroup(
            JuiceButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuiceButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JuiceText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        add(JuiceButton);

        SodaButton.setBackground(new java.awt.Color(246, 230, 230));
        SodaButton.setPreferredSize(new java.awt.Dimension(108, 100));

        SodaText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SodaText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SodaText.setText("Soda");
        SodaText.setAutoscrolls(true);

        javax.swing.GroupLayout SodaButtonLayout = new javax.swing.GroupLayout(SodaButton);
        SodaButton.setLayout(SodaButtonLayout);
        SodaButtonLayout.setHorizontalGroup(
            SodaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SodaButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SodaText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SodaButtonLayout.setVerticalGroup(
            SodaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SodaButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SodaText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        add(SodaButton);
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.Components.pnlBorder CoffeeButton;
    private javax.swing.JLabel CoffeeText;
    private GUI.Components.pnlBorder JuiceButton;
    private javax.swing.JLabel JuiceText;
    private GUI.Components.pnlBorder MilkAndCocoaButton;
    private javax.swing.JLabel MilkAndCocoaText;
    private GUI.Components.pnlBorder RecommentButton;
    private javax.swing.JLabel RecommentText;
    private GUI.Components.pnlBorder SodaButton;
    private javax.swing.JLabel SodaText;
    private GUI.Components.pnlBorder TeaButton;
    private javax.swing.JLabel TeaText;
    // End of variables declaration//GEN-END:variables
}
