/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.MenuComponent;

import java.awt.*;

/**
 *
 * @author Adam
 */
public class MenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel
     */
    public MenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drinkGUI1 = new GUI.MenuComponent.DrinkGUI();
        drinkGUI2 = new GUI.MenuComponent.DrinkGUI();
        drinkGUI3 = new GUI.MenuComponent.DrinkGUI();
        drinkGUI4 = new GUI.MenuComponent.DrinkGUI();
        drinkGUI5 = new GUI.MenuComponent.DrinkGUI();
        drinkGUI6 = new GUI.MenuComponent.DrinkGUI();
        drinkGUI7 = new GUI.MenuComponent.DrinkGUI();
        drinkGUI8 = new GUI.MenuComponent.DrinkGUI();

        setBackground(new java.awt.Color(137, 105, 112));
        setPreferredSize(new java.awt.Dimension(720, 534));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 10));
        add(drinkGUI1);
        add(drinkGUI2);
        add(drinkGUI3);
        add(drinkGUI4);
        add(drinkGUI5);
        add(drinkGUI6);
        add(drinkGUI7);
        add(drinkGUI8);
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.MenuComponent.DrinkGUI drinkGUI1;
    private GUI.MenuComponent.DrinkGUI drinkGUI2;
    private GUI.MenuComponent.DrinkGUI drinkGUI3;
    private GUI.MenuComponent.DrinkGUI drinkGUI4;
    private GUI.MenuComponent.DrinkGUI drinkGUI5;
    private GUI.MenuComponent.DrinkGUI drinkGUI6;
    private GUI.MenuComponent.DrinkGUI drinkGUI7;
    private GUI.MenuComponent.DrinkGUI drinkGUI8;
    // End of variables declaration//GEN-END:variables
}
