/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.MenuComponent;

import java.awt.Color;

/**
 *
 * @author Adam
 */
public class SweetnessLevelButton extends javax.swing.JPanel {

    /**
     * Creates new form FlowLayoutButton2
     */
    public SweetnessLevelButton() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        button0 = new GUI.Components.pnlBorder();
        text0 = new javax.swing.JLabel();
        button25 = new GUI.Components.pnlBorder();
        text25 = new javax.swing.JLabel();
        button50 = new GUI.Components.pnlBorder();
        text50 = new javax.swing.JLabel();
        button75 = new GUI.Components.pnlBorder();
        text75 = new javax.swing.JLabel();
        button100 = new GUI.Components.pnlBorder();
        text100 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(574, 45));

        button0.setBackground(new java.awt.Color(144, 111, 118));
        button0.setPreferredSize(new java.awt.Dimension(105, 35));

        text0.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        text0.setForeground(new java.awt.Color(255, 255, 255));
        text0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text0.setText("0%");

        javax.swing.GroupLayout button0Layout = new javax.swing.GroupLayout(button0);
        button0.setLayout(button0Layout);
        button0Layout.setHorizontalGroup(
            button0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text0, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        button0Layout.setVerticalGroup(
            button0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(button0);

        button25.setBackground(new java.awt.Color(144, 111, 118));
        button25.setPreferredSize(new java.awt.Dimension(105, 35));

        text25.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        text25.setForeground(new java.awt.Color(255, 255, 255));
        text25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text25.setText("25%");

        javax.swing.GroupLayout button25Layout = new javax.swing.GroupLayout(button25);
        button25.setLayout(button25Layout);
        button25Layout.setHorizontalGroup(
            button25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text25, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        button25Layout.setVerticalGroup(
            button25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(button25);

        button50.setBackground(new java.awt.Color(144, 111, 118));
        button50.setPreferredSize(new java.awt.Dimension(105, 35));

        text50.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        text50.setForeground(new java.awt.Color(255, 255, 255));
        text50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text50.setText("50%");

        javax.swing.GroupLayout button50Layout = new javax.swing.GroupLayout(button50);
        button50.setLayout(button50Layout);
        button50Layout.setHorizontalGroup(
            button50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button50Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text50, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        button50Layout.setVerticalGroup(
            button50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button50Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(button50);

        button75.setBackground(new java.awt.Color(144, 111, 118));
        button75.setPreferredSize(new java.awt.Dimension(105, 35));

        text75.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        text75.setForeground(new java.awt.Color(255, 255, 255));
        text75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text75.setText("75%");

        javax.swing.GroupLayout button75Layout = new javax.swing.GroupLayout(button75);
        button75.setLayout(button75Layout);
        button75Layout.setHorizontalGroup(
            button75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button75Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text75, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        button75Layout.setVerticalGroup(
            button75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button75Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(button75);

        button100.setBackground(new java.awt.Color(144, 111, 118));
        button100.setPreferredSize(new java.awt.Dimension(105, 35));

        text100.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        text100.setForeground(new java.awt.Color(255, 255, 255));
        text100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text100.setText("100%");

        javax.swing.GroupLayout button100Layout = new javax.swing.GroupLayout(button100);
        button100.setLayout(button100Layout);
        button100Layout.setHorizontalGroup(
            button100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button100Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text100, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        button100Layout.setVerticalGroup(
            button100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button100Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(button100);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.Components.pnlBorder button0;
    private GUI.Components.pnlBorder button100;
    private GUI.Components.pnlBorder button25;
    private GUI.Components.pnlBorder button50;
    private GUI.Components.pnlBorder button75;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel text0;
    private javax.swing.JLabel text100;
    private javax.swing.JLabel text25;
    private javax.swing.JLabel text50;
    private javax.swing.JLabel text75;
    // End of variables declaration//GEN-END:variables
}
