/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.MenuComponent;

import java.awt.Color;

/**
 *
 * @author Adam
 */
public class ToppingsButton extends javax.swing.JPanel {

    /**
     * Creates new form ToppingsButton
     */
    public ToppingsButton() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bubbleButton = new GUI.Components.pnlBorder();
        bubbleText = new javax.swing.JLabel();
        whipCreamButton = new GUI.Components.pnlBorder();
        whipCreamText = new javax.swing.JLabel();
        milkFoamButton = new GUI.Components.pnlBorder();
        milkFoamText = new javax.swing.JLabel();
        oreoButton = new GUI.Components.pnlBorder();
        oreoText = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(574, 45));

        bubbleButton.setBackground(new java.awt.Color(144, 111, 118));
        bubbleButton.setPreferredSize(new java.awt.Dimension(135, 35));
        bubbleButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bubbleText.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bubbleText.setForeground(new java.awt.Color(255, 255, 255));
        bubbleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bubbleText.setText("Bubble");
        bubbleButton.add(bubbleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 120, -1));

        add(bubbleButton);

        whipCreamButton.setBackground(new java.awt.Color(144, 111, 118));
        whipCreamButton.setPreferredSize(new java.awt.Dimension(135, 35));
        whipCreamButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        whipCreamText.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        whipCreamText.setForeground(new java.awt.Color(255, 255, 255));
        whipCreamText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        whipCreamText.setText("Whip cream");
        whipCreamButton.add(whipCreamText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 120, -1));

        add(whipCreamButton);

        milkFoamButton.setBackground(new java.awt.Color(144, 111, 118));
        milkFoamButton.setPreferredSize(new java.awt.Dimension(135, 35));
        milkFoamButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        milkFoamText.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        milkFoamText.setForeground(new java.awt.Color(255, 255, 255));
        milkFoamText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milkFoamText.setText("Milk Foam");
        milkFoamButton.add(milkFoamText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 120, -1));

        add(milkFoamButton);

        oreoButton.setBackground(new java.awt.Color(144, 111, 118));
        oreoButton.setPreferredSize(new java.awt.Dimension(135, 35));
        oreoButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        oreoText.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        oreoText.setForeground(new java.awt.Color(255, 255, 255));
        oreoText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oreoText.setText("Oreo");
        oreoButton.add(oreoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 110, -1));

        add(oreoButton);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.Components.pnlBorder bubbleButton;
    private javax.swing.JLabel bubbleText;
    private GUI.Components.pnlBorder milkFoamButton;
    private javax.swing.JLabel milkFoamText;
    private GUI.Components.pnlBorder oreoButton;
    private javax.swing.JLabel oreoText;
    private GUI.Components.pnlBorder whipCreamButton;
    private javax.swing.JLabel whipCreamText;
    // End of variables declaration//GEN-END:variables
}
