/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.MenuComponent;

import java.awt.Color;

/**
 *
 * @author Adam
 */
public class TypeOfDrink extends javax.swing.JPanel {

    /**
     * Creates new form HotIcedBlended
     */
    public TypeOfDrink() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBorder = new GUI.Components.pnlBorder();
        typeOfDrinkText = new javax.swing.JLabel();
        typeOfDrinkButton = new GUI.MenuComponent.TypeOfDrinkButton();

        pnlBorder.setBackground(new java.awt.Color(197, 158, 126));
        pnlBorder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typeOfDrinkText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        typeOfDrinkText.setForeground(new java.awt.Color(161, 65, 65));
        typeOfDrinkText.setText("Type of drink");
        pnlBorder.add(typeOfDrinkText, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 12, -1, 46));
        pnlBorder.add(typeOfDrinkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.Components.pnlBorder pnlBorder;
    private GUI.MenuComponent.TypeOfDrinkButton typeOfDrinkButton;
    private javax.swing.JLabel typeOfDrinkText;
    // End of variables declaration//GEN-END:variables
}
