/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.AdminUI;

import java.awt.Color;
import GUI.Components.AdminControl;
import GUI.Components.NavbarAdminGUI;
import java.awt.Color;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author admin
 */
public class AdminGUI extends javax.swing.JPanel {

    /**
     * Creates new form AdminStock
     */
    public AdminGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new GUI.Components.NavbarAdminGUI();
        adminControl1 = new GUI.Components.AdminControl();

        setBackground(new java.awt.Color(68, 55, 64));
        setPreferredSize(new java.awt.Dimension(720, 830));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        add(adminControl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 730));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.Components.AdminControl adminControl1;
    private GUI.Components.NavbarAdminGUI navbar;
    // End of variables declaration//GEN-END:variables
    
    public AdminControl getAdminControl() {
        return adminControl1;
    }

    public NavbarAdminGUI getNavbar() {
        return navbar;
    }
}
